@echo off
set PYTHONPATH=%cd%
echo Starting Hndl-it Browser Agent (Pure CDP)...
echo Ensuring dependencies...
pip install -r requirements.txt
echo Running Server...
python agents/browser/server.py
pause
